#!/bin/bash
#./build/main --epsilon 0.8
./build/main --batch-mode false --fit-subrange false --energy-cut true --epsilon-min 0.35 --epsilon-max 0.39 --epsilon-num 100 --output-file "of_data_testing_single_run.txt" #> "log_testing_single_run_EPS_"$EPSILON".txt"
#./build/main --batch-mode false --output-file "of_data_testing_single_run.txt" --filename "NewElectronNtuplizerExe_Int_ManDB_output.output.root" #> "log_testing_single_run_EPS_"$EPSILON".txt"
